### ISSUE TITLE
wrong jquery BOWER dependency id

### ISSUE THREAD

**Issue by igorlino** [tympanix/angular-table-resize#11]
Hi, 

(something easy to fix)

usually all bower components have ID that follows the naming convention, that is lowercase and without spaces.

Unfortunately an the angular-table-resize declares 
"jQuery": "^3.0.0"

could you please change it to lower case:

"jquery": "~3.1.0",

it creates problems with automated builds due to inconsistent directory creation.

Thanks

**Comment by tympanix** [comment]
This issue was pointed out a long time ago and was resolved. As you can see the [package.json](https://github.com/Tympanix/angular-table-resize/blob/master/package.json#L31) declares `jquery` spelled as you suggested. I can of course upgrade to version `3.1.0`. How you still see the old misspelled dependency is a mystery. Maybe try updating?

**Comment by tympanix** [comment]
Oh I see. The bower package is not on the latest version. I will update it asap 👍

**Comment by igorlino** [comment]
Thanks :+1:

**Comment by igorlino** [comment]
works fine. thanks gain.

Just for the sake of completeness for other users, the bower local registry needs to be cleanup:
1) In case you have them, remove your local jQuery directory. (bower_components)
2) Remove the bower cache from the local registry also:
C:\Users\<username>\AppData\Local\bower\cache\registry\bower.herokuapp.com\lookup
jquery_d223e
jQuery_f590b
