### ISSUE TITLE
The resizer undefined was not found

### ISSUE THREAD

**Issue by SoftCreatR** [tympanix/angular-table-resize#12]
I'm not sure, but this looks wrong:

```
    function getResizer(scope, attr) {
        try {
            var mode = attr.mode ? scope.mode : 'BasicResizer';
            var Resizer = $injector.get(mode)
            return Resizer;
        } catch (e) {
            console.error("The resizer " + scope.mode + " was not found");
            return null;
        }
    }
```

Shouldn't it be:

```
    function getResizer(scope, attr) {
        try {
            var mode = attr.mode ? attr.mode : 'BasicResizer';
            var Resizer = $injector.get(mode)
            return Resizer;
        } catch (e) {
            console.error("The resizer " + attr.mode + " was not found");
            return null;
        }
    }
```

**Comment by tympanix** [comment]
It shouldn't. The attribute `mode` is a two way binding - not a static value. This means that `attr.mode` will be the name of the variable on the scope and `scope.mode` will be the actual content of the variable. If you set the mode attribute to `BasicResizer` then it will look for a variable with that name on the scope, which is probably not what you intended. Since this variable doesn't exists (it is `undefined`) the resizer with name `undefined` can't be found.

Instead you should define a variable on your controller scope like this:
```javascript
$scope.myTableMode = "BasicResizer"
```

And then set your mode to `myTableMode` which will create a two way binding to that variable. I hope this answers the question 👍

**Comment by SoftCreatR** [comment]
I've set mode="FixedResizer" to the table and when i did, it came up with that error message. Maybe because i'm using Controller-As? However, after modifying the method above, it worked as intended.

**Comment by tympanix** [comment]
If you want to do it like the way you describe above, you need to give it a static value like so:
```javascript
mode="'FixedResizer'"
```
N.B. Note the qoutes (`'`) inside double qoutes (`"`).
